### ISSUE TITLE
login fails on live site: https://manager.pgxn.org/

### ISSUE THREAD

**Issue by palmerj** [pgxn/pgxn-manager#50]
I get the following stack trace:

install_driver(Pg) failed: Can't load '/var/virtuals/pgxn/perlbrew/perls/perl-5.14.2/lib/site_perl/5.14.2/x86_64-linux/auto/DBD/Pg/Pg.so' for module DBD::Pg: /lib/x86_64-linux-gnu/libresolv.so.2: symbol __h_errno, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference at /var/virtuals/pgxn/perlbrew/perls/perl-5.14.2/lib/5.14.2/x86_64-linux/DynaLoader.pm line 190.
 at (eval 364) line 3.
Compilation failed in require at (eval 364) line 3.
Perhaps a required shared library or dll isn't installed where expected
 at /var/virtuals/pgxn/perlbrew/perls/perl-5.14.2/lib/site_perl/5.14.2/DBIx/Connector.pm line 32.
 at /var/virtuals/pgxn/perlbrew/perls/perl-5.14.2/lib/site_perl/5.14.2/Plack/Middleware/StackTrace.pm line 23

**Comment by theory** [comment]
Back now, thanks.

**Comment by theory** [comment]
Not sure what happened, but restarting the proxy and the service fixed the issue.

**Comment by palmerj** [comment]
Thanks.

**Comment by depesz** [comment]
There was one more issue, due to problems with upgrade of PostgreSQL on the server, but service should be 100% up and stable now.
