### ISSUE TITLE
“xxx-1.4.2.tgz” doesn’t look like a distribution archive

### ISSUE THREAD

**Issue by strk** [pgxn/pgxn-manager#61]
I'm getting such message upon uploading a tgz file for "releasing" it to the public, but the message doesn't tell me what's wrong in it. The tarball unpacks in a directory with the name of the extension and does contain a META.json file. For a quick look I uploaded it on this temporary URL: http://strk.kbt.io/tmp/table_version-1.4.2.tgz - can you see what's wrong with it ?

It would be helpful if the UI would tell what's lacking/missing/doing wrong

**Comment by theory** [comment]
Yes, that certainly looks fine. I ran my validator on the META.json and it worked. I wonder if something is missing from the PGXN manager config since the server upgrade last week…

**Comment by theory** [comment]
Would you post a screenshot of the response, please? I'm not able to replicate the issue, and there's nothing in the logs. :-(

**Comment by strk** [comment]
![screenshot at 2018-04-05 15-42-29](https://user-images.githubusercontent.com/289678/38369479-163c81e4-38e8-11e8-82e8-6addeb085a98.png)

**Comment by theory** [comment]
Try renaming the file to end in `.tar.gz` rather than `.tgz`.

**Comment by strk** [comment]
I tried both, the screenshot is for `.tar.gz` while the original report was for `.tgz` (same file, just renamed)

**Comment by theory** [comment]
Hrm. I just wrote a script trying to duplicate, and it worked, no error. WTF…

**Comment by theory** [comment]
I'll keep at it, but meanwhile, try uploading a zip file, instead.

**Comment by strk** [comment]
.zip worked

**Comment by theory** [comment]
So [I see](https://twitter.com/pgxn/status/981913904799416321). WTF.

**Comment by beaud76** [comment]
Hi, I have had exactly the same problem yesterday with a new release of the E-Maj extension (2.3.0). Same message, same input formats (tar.gz and tgz), and same workaround by using a zip file. The tgz file is quite large: 4.3 Mb. But I tried with a smaller one (2.3Mb) with no success. 
Here is the faulting file:
[emaj-2.3.0.tar.gz](https://github.com/pgxn/pgxn-manager/files/2176416/emaj-2.3.0.tar.gz)
