### ISSUE TITLE
reference on PostgreSQL 10 fails

### ISSUE THREAD

**Issue by okbob** [pgxn/pgxn-manager#62]
I try to upload new release of orafce
I got a error

Field /prereqs/runtime/recommends/PostgreSQL: "10.0" is not a valid semantic version [Spec v1.0.0] 

https://github.com/orafce/orafce/blob/master/META.json

**Comment by theory** [comment]
Make it `10.0.0`. Yes, I know that Postgres no longer uses thre-part versions, but PGXN requires semantic versions, so you have to specify the semantic-version equivalent.
