### ISSUE TITLE
release fails because of conflict with version that does not exist

### ISSUE THREAD

**Issue by tvondra** [pgxn/pgxn-manager#65]
Hi, I've tried to release a new version of the `quantile` extension, namely 1.1.7, but when I try to upload it through the web I get this failure:

```
One or more extension versions are less than previous versions:
* “quantile 1.1.7” < “quantile 1.2.0” 
```

Which is pretty strange, because I've never released 1.2.0 and it's not listed in "your distributions" either.

**Comment by theory** [comment]
Sorry the delayed reply, @tvondra. It looks like quantile 1.2.0 was included in the [trimmed_aggregates 1.2.0 distribution](https://pgxn.org/dist/trimmed_aggregates/1.2.0/) ([META.json]((https://api.pgxn.org/src/trimmed_aggregates/trimmed_aggregates-1.2.0/META.json)). Maybe that was a copy/paste error? Alas, I don't have a way to delete distributions, yet, but I believe I can reindex the trimmed_aggregates 1.2.0 (and 1.0.0, same issue there) distributions if the only error in those versions was the extension name. Send me the zip files and I'll give it a try.

**Comment by tvondra** [comment]
Yeah, that's definitely a copy-pasto.

**Comment by tvondra** [comment]
OK, the modified releases are here: https://drive.google.com/drive/folders/1JWh4FUH_sr8qaUg6tjLg7CkgLS4YifVa

I wonder if this could be an attack vector for extensions from other people. I haven't tried, but what's stopping me from releasing an extension with conflicting META.json for extension owned by someone else?

**Comment by tvondra** [comment]
Any news about this? Should I try uploading the release again?

**Comment by theory** [comment]
My apologies, I somehow missed the notification when you replied with the new zip files. I've reindexed them, and now [it looks better](https://api.pgxn.org/src/trimmed_aggregates/trimmed_aggregates-1.2.0/META.json). You should be able to release quantile 1.1.7 now.

Apologies for the delay.
