### ISSUE TITLE
Ow ow ow -error

### ISSUE THREAD

**Issue by marcmunro** [pgxn/pgxn-manager#67]
Trying to release pgbitmap-0.9.3.zip gave me this error:

Whoops! Some sort of error occurred. We apologise for the fault in the server. Those responsible have been sacked. Mynd you, elephänt bites kan be pretty nasti…Please do try again.

I wish I had more to give you but I don't.  This was at about 15:40 PST on 2020/10/13

I have attached the zip file.
__
Marc

**Comment by theory** [comment]
It's not your distribution, it's something to do with the upgrade to Postgres 13. I'm investigating now.

**Comment by marcmunro** [comment]
On Sat, 2020-10-17 at 13:37 -0700, David E. Wheeler wrote:
> It's not your distribution, it's something to do with the upgrade to
> Postgres 13. I'm investigating now.

Great, thank you.  That's reassuring as I was quite baffled and no
longer have enough hair to pull out.

__
Marc

**Comment by theory** [comment]
So sorry about your hair!

Turns out as of Postgres 12 the semver extension needs to be explicit with collations. It was just upgraded from 11. So there we go. Working on a fix now, should be back in business sometime tomorrow.

**Comment by theory** [comment]
I just successfully released semver-0.31.0, which was what needed to be fixed, so should be all good now. Give it another try.

**Comment by marcmunro** [comment]
David, thank you.  The problem has gone and I have been able to upload my extension.  This bug can be closed.
