### ISSUE TITLE
Request Account page asks for authentication

### ISSUE THREAD

**Issue by ankane** [pgxn/pgxn-manager#70]
Hi, thanks for the great work on PGXN!

The Request Account link on the [FAQ page](https://pgxn.org/faq/) points to https://manager.pgxn.org/account/register, which prompts for authentication.

**Comment by theory** [comment]
It should work if you're not currently logged in (https is authenticated only, http is non-autenticted). But right now I'm seeing the same thing. Might have messed up the configuration to always auto-redirect to https, which we don't actually want. Weirdly, I don't see the redirect header I'd expect when I use curl:

```
 curl -I http://manager.pgxn.org/account/register
HTTP/1.1 200 OK
Server: nginx/1.14.2
Date: Wed, 05 May 2021 00:09:24 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 5153
Connection: keep-alive
Set-Cookie: plack_session=b40d022e6b255f9d819bd947e00ca7ed6d6c4bc4; path=/
```

So not sure why it redirects.

**Comment by theory** [comment]
It worked correctly when I cleared my browser's data. So you must have an account that you've used, @ankane, and your browser thinks you meant to use https and should log in.

I suspect browsers are being more aggressive in preferring https when they know it's an option. Which it isn't here. Might have to hunt around for a header config or something to tell it to knock it off. Long term, should revamp PGXN Manager to use https only and not rely on basic auth for authentication.

**Comment by ankane** [comment]
Ah, interesting. My browser is configured to prefer HTTPS, so that's probably the cause. The HTTP link works when I try another browser.

+1 for the HTTPS only plan (also noticed the mirrors use HTTP). From a security/privacy perspective, it'd be good for the registration page to require HTTPS.

**Comment by ankane** [comment]
Thanks @theory! Will test it once it's deployed.

**Comment by ankane** [comment]
Just to follow up: working great  🎉 

Also looked into the mirrors. It looks like pgxnclient uses https://api.pgxn.org by default. The `mirror` command calls https://api.pgxn.org/meta/mirrors.json, which returns:

```
http://pgxn.dalibo.org/
http://api.pgxn.org/
```

It looks like both subdomains support HTTPS, so may make sense to update the `mirrors.json` file.

**Comment by theory** [comment]
Done, good call, thanks!
