### ISSUE TITLE
List only Latest release of each Extension in the Recent Releases pane

### ISSUE THREAD

**Issue by theory** [pgxn/pgxn-manager#71]
A user making frequent releases of an extension can come to have all of the recent releases listing their extension. Consider modifying it to show only the most recent release of each extension, so they're only listed once.

**Comment by RekGRpth** [comment]
> to show only the most recent release of each extension, so they're only listed once

It is a right solution.

**Comment by theory** [comment]
To be clear, @RekGRpth, that will make the display on [the site](https://pgxn.org/recent/) less duplicative, but it won't undo [tweets](https://twitter.com/pgxn). It would still be better for extension authors to be intentional and thoughtful about releases, and not make them multiple times a day for one extension, so as to avoid the perception of spamming.

**Comment by theory** [comment]
Fixed in pgxn/pgxn-site@880c0b7 for display on the site. I think it best to leave the dupes here for completeness.
