### ISSUE TITLE
Incorrect Escaping of Makfile example in HOW-TO

### ISSUE THREAD

**Issue by theory** [pgxn/pgxn-manager#76]
the example Makefile in the how-to has incorrect escaping for EXTENSION/EXTVERSION/DISTVERSION.  Backslashes aren’t supposed to be escaped.  The examples on github (pair, etc) are correct.

**Comment by IshaanAdarsh** [comment]
I would like to fix this, could you assign this to me.

**Comment by theory** [comment]
Ugh, this appears to be a rendering bug. Need to switch markdown parsers as described in #77.
