### ISSUE TITLE
Remove all pg_text_semver packages prior to version 1.2.1

### ISSUE THREAD

**Issue by bigsmoke** [pgxn/pgxn-manager#84]
Due to a copy-paste error, all my `pg_text_semver` releases prior to `pg_text_semver` 1.2.1 had a bad key in the `provides` object in `META.json`: `pg_safer_settings` instead of `pg_text_semver`.

However, I don't see any way to remove faulty distributions from PGXN. Is there any way for all `pg_text_semver` releases prior to `pg_text_semver` 1.2.1 to be deleted?

**Comment by theory** [comment]
There is not. That data is mainly used to show the list of included extensions on the web page, and will be fixed in the next release you upload, though older ones will still show the wrong name.

**Comment by bigsmoke** [comment]
Ah, ok; so no risk of people accidentally installing `pg_text_semver` when they try to install `pg_safer_settings` through the `pgxn` program? 😌

**Comment by theory** [comment]
No, that corresponds to the distribution name, not the individual extension.

**Comment by bigsmoke** [comment]
Ah good. Thank you for explaining!
